# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrandTagsController do

  # This should return the minimal set of attributes required to create a valid
  # BrandTag. As you add validations to BrandTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrandTagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all brand_tags as @brand_tags" do
      brand_tag = BrandTag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:brand_tags).should eq([brand_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested brand_tag as @brand_tag" do
      brand_tag = BrandTag.create! valid_attributes
      get :show, {:id => brand_tag.to_param}, valid_session
      assigns(:brand_tag).should eq(brand_tag)
    end
  end

  describe "GET new" do
    it "assigns a new brand_tag as @brand_tag" do
      get :new, {}, valid_session
      assigns(:brand_tag).should be_a_new(BrandTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested brand_tag as @brand_tag" do
      brand_tag = BrandTag.create! valid_attributes
      get :edit, {:id => brand_tag.to_param}, valid_session
      assigns(:brand_tag).should eq(brand_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BrandTag" do
        expect {
          post :create, {:brand_tag => valid_attributes}, valid_session
        }.to change(BrandTag, :count).by(1)
      end

      it "assigns a newly created brand_tag as @brand_tag" do
        post :create, {:brand_tag => valid_attributes}, valid_session
        assigns(:brand_tag).should be_a(BrandTag)
        assigns(:brand_tag).should be_persisted
      end

      it "redirects to the created brand_tag" do
        post :create, {:brand_tag => valid_attributes}, valid_session
        response.should redirect_to(BrandTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brand_tag as @brand_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        BrandTag.any_instance.stub(:save).and_return(false)
        post :create, {:brand_tag => { "name" => "invalid value" }}, valid_session
        assigns(:brand_tag).should be_a_new(BrandTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BrandTag.any_instance.stub(:save).and_return(false)
        post :create, {:brand_tag => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brand_tag" do
        brand_tag = BrandTag.create! valid_attributes
        # Assuming there are no other brand_tags in the database, this
        # specifies that the BrandTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BrandTag.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => brand_tag.to_param, :brand_tag => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested brand_tag as @brand_tag" do
        brand_tag = BrandTag.create! valid_attributes
        put :update, {:id => brand_tag.to_param, :brand_tag => valid_attributes}, valid_session
        assigns(:brand_tag).should eq(brand_tag)
      end

      it "redirects to the brand_tag" do
        brand_tag = BrandTag.create! valid_attributes
        put :update, {:id => brand_tag.to_param, :brand_tag => valid_attributes}, valid_session
        response.should redirect_to(brand_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the brand_tag as @brand_tag" do
        brand_tag = BrandTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BrandTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => brand_tag.to_param, :brand_tag => { "name" => "invalid value" }}, valid_session
        assigns(:brand_tag).should eq(brand_tag)
      end

      it "re-renders the 'edit' template" do
        brand_tag = BrandTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BrandTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => brand_tag.to_param, :brand_tag => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brand_tag" do
      brand_tag = BrandTag.create! valid_attributes
      expect {
        delete :destroy, {:id => brand_tag.to_param}, valid_session
      }.to change(BrandTag, :count).by(-1)
    end

    it "redirects to the brand_tags list" do
      brand_tag = BrandTag.create! valid_attributes
      delete :destroy, {:id => brand_tag.to_param}, valid_session
      response.should redirect_to(brand_tags_url)
    end
  end

end
