# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DarenAppliesController do

  # This should return the minimal set of attributes required to create a valid
  # DarenApply. As you add validations to DarenApply, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DarenAppliesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all daren_applies as @daren_applies" do
      daren_apply = DarenApply.create! valid_attributes
      get :index, {}, valid_session
      assigns(:daren_applies).should eq([daren_apply])
    end
  end

  describe "GET show" do
    it "assigns the requested daren_apply as @daren_apply" do
      daren_apply = DarenApply.create! valid_attributes
      get :show, {:id => daren_apply.to_param}, valid_session
      assigns(:daren_apply).should eq(daren_apply)
    end
  end

  describe "GET new" do
    it "assigns a new daren_apply as @daren_apply" do
      get :new, {}, valid_session
      assigns(:daren_apply).should be_a_new(DarenApply)
    end
  end

  describe "GET edit" do
    it "assigns the requested daren_apply as @daren_apply" do
      daren_apply = DarenApply.create! valid_attributes
      get :edit, {:id => daren_apply.to_param}, valid_session
      assigns(:daren_apply).should eq(daren_apply)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DarenApply" do
        expect {
          post :create, {:daren_apply => valid_attributes}, valid_session
        }.to change(DarenApply, :count).by(1)
      end

      it "assigns a newly created daren_apply as @daren_apply" do
        post :create, {:daren_apply => valid_attributes}, valid_session
        assigns(:daren_apply).should be_a(DarenApply)
        assigns(:daren_apply).should be_persisted
      end

      it "redirects to the created daren_apply" do
        post :create, {:daren_apply => valid_attributes}, valid_session
        response.should redirect_to(DarenApply.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved daren_apply as @daren_apply" do
        # Trigger the behavior that occurs when invalid params are submitted
        DarenApply.any_instance.stub(:save).and_return(false)
        post :create, {:daren_apply => { "user_id" => "invalid value" }}, valid_session
        assigns(:daren_apply).should be_a_new(DarenApply)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DarenApply.any_instance.stub(:save).and_return(false)
        post :create, {:daren_apply => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested daren_apply" do
        daren_apply = DarenApply.create! valid_attributes
        # Assuming there are no other daren_applies in the database, this
        # specifies that the DarenApply created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DarenApply.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => daren_apply.to_param, :daren_apply => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested daren_apply as @daren_apply" do
        daren_apply = DarenApply.create! valid_attributes
        put :update, {:id => daren_apply.to_param, :daren_apply => valid_attributes}, valid_session
        assigns(:daren_apply).should eq(daren_apply)
      end

      it "redirects to the daren_apply" do
        daren_apply = DarenApply.create! valid_attributes
        put :update, {:id => daren_apply.to_param, :daren_apply => valid_attributes}, valid_session
        response.should redirect_to(daren_apply)
      end
    end

    describe "with invalid params" do
      it "assigns the daren_apply as @daren_apply" do
        daren_apply = DarenApply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DarenApply.any_instance.stub(:save).and_return(false)
        put :update, {:id => daren_apply.to_param, :daren_apply => { "user_id" => "invalid value" }}, valid_session
        assigns(:daren_apply).should eq(daren_apply)
      end

      it "re-renders the 'edit' template" do
        daren_apply = DarenApply.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DarenApply.any_instance.stub(:save).and_return(false)
        put :update, {:id => daren_apply.to_param, :daren_apply => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested daren_apply" do
      daren_apply = DarenApply.create! valid_attributes
      expect {
        delete :destroy, {:id => daren_apply.to_param}, valid_session
      }.to change(DarenApply, :count).by(-1)
    end

    it "redirects to the daren_applies list" do
      daren_apply = DarenApply.create! valid_attributes
      delete :destroy, {:id => daren_apply.to_param}, valid_session
      response.should redirect_to(daren_applies_url)
    end
  end

end
