# -*- encoding : utf-8 -*-
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DftiesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dfty. As you add validations to Dfty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DftiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dfties as @dfties" do
      dfty = Dfty.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dfties)).to eq([dfty])
    end
  end

  describe "GET show" do
    it "assigns the requested dfty as @dfty" do
      dfty = Dfty.create! valid_attributes
      get :show, {:id => dfty.to_param}, valid_session
      expect(assigns(:dfty)).to eq(dfty)
    end
  end

  describe "GET new" do
    it "assigns a new dfty as @dfty" do
      get :new, {}, valid_session
      expect(assigns(:dfty)).to be_a_new(Dfty)
    end
  end

  describe "GET edit" do
    it "assigns the requested dfty as @dfty" do
      dfty = Dfty.create! valid_attributes
      get :edit, {:id => dfty.to_param}, valid_session
      expect(assigns(:dfty)).to eq(dfty)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dfty" do
        expect {
          post :create, {:dfty => valid_attributes}, valid_session
        }.to change(Dfty, :count).by(1)
      end

      it "assigns a newly created dfty as @dfty" do
        post :create, {:dfty => valid_attributes}, valid_session
        expect(assigns(:dfty)).to be_a(Dfty)
        expect(assigns(:dfty)).to be_persisted
      end

      it "redirects to the created dfty" do
        post :create, {:dfty => valid_attributes}, valid_session
        expect(response).to redirect_to(Dfty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dfty as @dfty" do
        post :create, {:dfty => invalid_attributes}, valid_session
        expect(assigns(:dfty)).to be_a_new(Dfty)
      end

      it "re-renders the 'new' template" do
        post :create, {:dfty => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dfty" do
        dfty = Dfty.create! valid_attributes
        put :update, {:id => dfty.to_param, :dfty => new_attributes}, valid_session
        dfty.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dfty as @dfty" do
        dfty = Dfty.create! valid_attributes
        put :update, {:id => dfty.to_param, :dfty => valid_attributes}, valid_session
        expect(assigns(:dfty)).to eq(dfty)
      end

      it "redirects to the dfty" do
        dfty = Dfty.create! valid_attributes
        put :update, {:id => dfty.to_param, :dfty => valid_attributes}, valid_session
        expect(response).to redirect_to(dfty)
      end
    end

    describe "with invalid params" do
      it "assigns the dfty as @dfty" do
        dfty = Dfty.create! valid_attributes
        put :update, {:id => dfty.to_param, :dfty => invalid_attributes}, valid_session
        expect(assigns(:dfty)).to eq(dfty)
      end

      it "re-renders the 'edit' template" do
        dfty = Dfty.create! valid_attributes
        put :update, {:id => dfty.to_param, :dfty => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dfty" do
      dfty = Dfty.create! valid_attributes
      expect {
        delete :destroy, {:id => dfty.to_param}, valid_session
      }.to change(Dfty, :count).by(-1)
    end

    it "redirects to the dfties list" do
      dfty = Dfty.create! valid_attributes
      delete :destroy, {:id => dfty.to_param}, valid_session
      expect(response).to redirect_to(dfties_url)
    end
  end

end
