# -*- encoding : utf-8 -*-
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JoinLotteriesController do

  # This should return the minimal set of attributes required to create a valid
  # JoinLottery. As you add validations to JoinLottery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JoinLotteriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all join_lotteries as @join_lotteries" do
      join_lottery = JoinLottery.create! valid_attributes
      get :index, {}, valid_session
      assigns(:join_lotteries).should eq([join_lottery])
    end
  end

  describe "GET show" do
    it "assigns the requested join_lottery as @join_lottery" do
      join_lottery = JoinLottery.create! valid_attributes
      get :show, {:id => join_lottery.to_param}, valid_session
      assigns(:join_lottery).should eq(join_lottery)
    end
  end

  describe "GET new" do
    it "assigns a new join_lottery as @join_lottery" do
      get :new, {}, valid_session
      assigns(:join_lottery).should be_a_new(JoinLottery)
    end
  end

  describe "GET edit" do
    it "assigns the requested join_lottery as @join_lottery" do
      join_lottery = JoinLottery.create! valid_attributes
      get :edit, {:id => join_lottery.to_param}, valid_session
      assigns(:join_lottery).should eq(join_lottery)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JoinLottery" do
        expect {
          post :create, {:join_lottery => valid_attributes}, valid_session
        }.to change(JoinLottery, :count).by(1)
      end

      it "assigns a newly created join_lottery as @join_lottery" do
        post :create, {:join_lottery => valid_attributes}, valid_session
        assigns(:join_lottery).should be_a(JoinLottery)
        assigns(:join_lottery).should be_persisted
      end

      it "redirects to the created join_lottery" do
        post :create, {:join_lottery => valid_attributes}, valid_session
        response.should redirect_to(JoinLottery.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved join_lottery as @join_lottery" do
        # Trigger the behavior that occurs when invalid params are submitted
        JoinLottery.any_instance.stub(:save).and_return(false)
        post :create, {:join_lottery => { "user_id" => "invalid value" }}, valid_session
        assigns(:join_lottery).should be_a_new(JoinLottery)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JoinLottery.any_instance.stub(:save).and_return(false)
        post :create, {:join_lottery => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested join_lottery" do
        join_lottery = JoinLottery.create! valid_attributes
        # Assuming there are no other join_lotteries in the database, this
        # specifies that the JoinLottery created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JoinLottery.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => join_lottery.to_param, :join_lottery => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested join_lottery as @join_lottery" do
        join_lottery = JoinLottery.create! valid_attributes
        put :update, {:id => join_lottery.to_param, :join_lottery => valid_attributes}, valid_session
        assigns(:join_lottery).should eq(join_lottery)
      end

      it "redirects to the join_lottery" do
        join_lottery = JoinLottery.create! valid_attributes
        put :update, {:id => join_lottery.to_param, :join_lottery => valid_attributes}, valid_session
        response.should redirect_to(join_lottery)
      end
    end

    describe "with invalid params" do
      it "assigns the join_lottery as @join_lottery" do
        join_lottery = JoinLottery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JoinLottery.any_instance.stub(:save).and_return(false)
        put :update, {:id => join_lottery.to_param, :join_lottery => { "user_id" => "invalid value" }}, valid_session
        assigns(:join_lottery).should eq(join_lottery)
      end

      it "re-renders the 'edit' template" do
        join_lottery = JoinLottery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JoinLottery.any_instance.stub(:save).and_return(false)
        put :update, {:id => join_lottery.to_param, :join_lottery => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested join_lottery" do
      join_lottery = JoinLottery.create! valid_attributes
      expect {
        delete :destroy, {:id => join_lottery.to_param}, valid_session
      }.to change(JoinLottery, :count).by(-1)
    end

    it "redirects to the join_lotteries list" do
      join_lottery = JoinLottery.create! valid_attributes
      delete :destroy, {:id => join_lottery.to_param}, valid_session
      response.should redirect_to(join_lotteries_url)
    end
  end

end
